/*
Copyright (c) 2003-2010, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.html or http://ckeditor.com/license
*/

CKEDITOR.addTemplates('default',{
    imagesPath:CKEDITOR.getUrl(CKEDITOR.plugins.getPath('templates')+'templates/images/'),
    templates:[{
        title:'Expertise',
        image:'template5.jpg',
        description:'A title with some text and a table.',
        html:'<div class="contentBottom"><div class="contentLeft"><div class="title">Stratton Reede  difference</div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus. Mauris commodo scelerisque tellus, nec ullamcorper eros imperdiet id. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed </p><div class="decription"><div class="decriptionLeft"><p><strong>Lorem ipsum</strong> dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p><strong>Lorem ipsum</strong> dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p><strong>Lorem ipsum</strong> dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p></div><div class="decriptionRight"><p><strong>Lorem ipsum</strong> dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p><strong>Lorem ipsum</strong> dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p><strong>Lorem ipsum</strong> dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p></div><div class="clr"></div></div></div><div class="contentRight"><div class="highlights"><div class="newsTitle">Lorem ipsum</div><p>dolor sit amet, consectetur adipiscing elit.</p><p> Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p>Mauris commodo scelerisque tellus, nec ullamcorper eros imperdiet id.</p></div></div><div class="clr"></div></div>'
    },{
        title:'Company',
        image:'template6.jpg',
        description:'A title with some text and a table.',
        html:'<div class="contentBottom"><div class="contentLeft"><div class="title">What We Do</div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus. Mauris commodo scelerisque tellus, nec ullamcorper eros imperdiet id. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed varius, nisi et fermentum posuere, leo dolor egestas purus, nec dapibus odio leo viverra est. In hac habitasse platea dictumst.</p><p>Quisque vestibulum dapibus elit, vitae convallis elit egestas ut. Vivamus volutpat aliquet erat, nec rhoncus dolor consectetur nec. Suspendisse posuere aliquam augue, id varius odio viverra fringilla. Fusce in interdum leo. Vivamus facilisis fringilla vestibulum.</p><p>In hac habitasse platea dictumst. Duis auctor, nulla quis viverra rutrum, libero purus laoreet sem, eget faucibus eros augue ac orci. Ut cursus sollicitudin blandit. Fusce bibendum massa quis nisi blandit vitae auctor ante ultrices. Nulla accumsan placerat lorem, molestie luctus augue facilisis sed. Aliquam erat volutpat.</p><p>Quisque vestibulum dapibus elit, vitae convallis elit egestas ut. Vivamus volutpat aliquet erat, nec rhoncus dolor consectetur nec. Suspendisse posuere aliquam augue, id varius odio viverra fringilla. Fusce in interdum leo. Vivamus facilisis fringilla vestibulum.</p></div><div class="contentRight"><div class="highlights"><div class="newsTitle">Lorem ipsum</div><p>dolor sit amet, consectetur adipiscing elit.</p><p> Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p>Mauris commodo scelerisque tellus, nec ullamcorper eros imperdiet id.</p></div><div class="subscribeBttn"><a href="#">Subscribe to Newsletter</a></div></div><div class="clr"></div></div>'
    },{
        title:'Three column',
        image:'template7.jpg',
        description:'A title with some text and a table.',
        html:'<div class="contentBottom"><div class="uppercontentBottom"><div class="title">Three steps to success</div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus. Mauris commodo scelerisque tellus, nec ullamcorper eros imperdiet id. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed </p></div><div class="lowerContent"><div class="colThree marLeft30"><div class="title"><div class="numbering">1</div><div class="heading">Heading one</div><div class="clr"></div></div><p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ti</strong></p><p> ncidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula,</p></div><div class="colThree marLeft30"><div class="title"><div class="numbering">2</div><div class="heading">Heading one</div><div class="clr"></div></div><p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ti</strong> </p><p>ncidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula,</p></div><div class="colThree"><div class="title"><div class="numbering">3</div><div class="heading">Heading one</div><div class="clr"></div></div><p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ti</strong></p><p> ncidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula, sit amet laoreet velit mauris non lacus.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt, mauris nec placerat tincidunt, felis sem hendrerit ligula,</p></div><div class="clr"></div></div></div>'
    }]
});
